name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Ruby for use with actions
        uses: actions/setup-ruby@v1.1.2
          
      - name: Bundle - check version
        run: bundle -v
      
      # Have to cd every time
      # Every command is isolated and position is not persistant
      - name: Install just-the-docs
        working-directory: ./docs
        run: gem install just-the-docs
      
      - name: Install jenkyll plugins
        working-directory: ./docs
        run: bundle install --full-index

      - name: Create search engine
        working-directory: ./docs
        run: bundle exec just-the-docs rake search:init

      - name: Build website
        working-directory: ./docs
        run: bundle exec jekyll build

      - name: Create output folder
        run: mkdir ./releaseFolder

      - name: Move built doc
        run: |
          mv ./docs/_site ./releaseFolder/docs
          rm -fr ./docs/
        
      - name: Move landing static page
        run: find . -maxdepth 1 -not -name ".*" -not -name "releaseFolder" -exec mv {} ./releaseFolder \;

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          # GitHub repository where assets will be deployed (default current)
          #repo: # optional
          # Git branch where assets will be deployed
          #target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          keep_history: false
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: ./releaseFolder
          # Commit author's name
          committer_name: Github Actions
          # Commit author's email
          committer_email: actions@github.com
          # Commit message
          #commit_message: # optional
          # Write the given domain name to the CNAME file
          fqdn: comokit.org # optional  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT_ROIARTHURB }}
