name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Ruby for use with actions
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.0.5
          
      - name: Bundle - check version
        run: |
          gem install bundler -v '~> 2.3.5'
          bundle -v # Should be 2.3.X
      
      # Have to cd every time
      # Every command is isolated and position is not persistant
      - name: Install just-the-docs
        working-directory: ./docs
        run: gem install just-the-docs
      
      - name: Install jenkyll plugins
        working-directory: ./docs
        run: bundle install --full-index

      - name: Create search engine
        working-directory: ./docs
        run: bundle exec just-the-docs rake search:init

      - name: Build website
        working-directory: ./docs
        run: bundle exec jekyll build

      - name: Create output folder
        run: mkdir ./releaseFolder

      - name: Move built doc
        run: |
          mv ./docs/_site ./releaseFolder/docs
          rm -fr ./docs/
        
      - name: Move landing static page
        run: find . -maxdepth 1 -not -name ".*" -not -name "releaseFolder" -exec mv {} ./releaseFolder \;

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: ./releaseFolder
          # Allow Jekyll to build your site (default true)
          jekyll: false
          # Write the given domain name to the CNAME file
          fqdn: comokit.org # optional  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
