name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Ruby for use with actions
        uses: actions/setup-ruby@v1.0.0
          
      - name: Bundle - check version
        run: bundle -v
      
      # Have to cd every time
      # Every command is isolated and position is not persistant
      - name: Install just-the-docs
        run: cd docs && gem install just-the-docs
      
      - name: Install jenkyll plugins
        run: cd docs && bundle install --full-index

      - name: Create search engine
        run: cd docs && bundle exec just-the-docs rake search:init

      - name: Build website
        run: cd docs && bundle exec jekyll build

      - name: Prepare release folder
        run: mkdir ./releaseFolder && mv ./docs/_site ./releaseFolder/docs && rm -fr ./docs/ && find . -maxdepth 1 -wholename "./[a-Z]*" -not -name "releaseFolder" -exec mv {} releaseFolder \;

      - name: Check content before releasing
        run: tree -L 3 -a

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          # GitHub repository where assets will be deployed (default current)
          #repo: # optional
          # Git branch where assets will be deployed
          #target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          keep_history: false
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: ./releaseFolder
          # Commit author's name
          committer_name: Github Actions
          # Commit author's email
          committer_email: actions@github.com
          # Commit message
          #commit_message: # optional
          # Write the given domain name to the CNAME file
          #fqdn: # optional  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT_ROIARTHURB }}
